/* login */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO';

export const REQUEST_DATA = 'REQUEST_DATA';

/* apply */
export const GET_APPLY_DATA = 'GET_APPLY_DATA';
export const GET_APPLY_DATA_SUCCESS = 'GET_APPLY_DATA_SUCCESS';
export const GET_CONTACT_DATA = 'GET_CONTACT_DATA';
export const GET_CONTACT_DATA_SUCCESS = 'GET_CONTACT_DATA_SUCCESS';
export const ADD_CONTACT_DATA = 'ADD_CONTACT_DATA';
export const ADD_CONTACT_DATA_SUCCESS = 'ADD_CONTACT_DATA_SUCCESS';

/* case */
export const GET_CASE_DATA = 'GET_CASE_DATA';
export const GET_CASE_DATA_SUCCESS = 'GET_CASE_DATA_SUCCESS';

export const GET_CASE_DETAIL_REQUEST = 'GET_CASE_DETAIL_REQUEST';
export const GET_CASE_DETAIL_SUCCESS = 'GET_CASE_DETAIL_SUCCESS';

export const GET_DRAFT_DATA = 'GET_DRAFT_DATA';
export const GET_DRAFT_DATA_SUCCESS = 'GET_DRAFT_DATA_SUCCESS';

export const GET_DRAFT_DETAIL_REQUEST = 'GET_DRAFT_DETAIL_REQUEST';
export const GET_DRAFT_DETAIL_SUCCESS = 'GET_DRAFT_DETAIL_SUCCESS';

export const RESET_DRAFT_DETAIL_SUCCESS = 'RESET_DRAFT_DETAIL_SUCCESS';

export const GET_SEARCH_DATA = 'GET_SEARCH_DATA';